api_platform:
    title: MyJProgress API
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
